# worker-node.tf

resource "aws_instance" "worker" {

count = var.worker_count

ami                    = var.ami_id
instance_type          = var.worker_instance_type
subnet_id              = aws_subnet.public.id
key_name               = var.key_name
associate_public_ip_address = true

vpc_security_group_ids = [
aws_security_group.kubeadm_cluster.id
]

tags = {
Name        = "worker-${count.index + 1}"
Environment = var.environment
}
}

resource "null_resource" "worker_setup" {

count = var.worker_count

depends_on = [
aws_instance.worker,
null_resource.control_plane_setup
]

connection {
type        = "ssh"
user        = "ubuntu"
host        = aws_instance.worker[count.index].public_ip
private_key = file(var.private_key_path)
}

#

# Upload worker bootstrap script

#

provisioner "file" {
source      = "./scripts/worker-node-cmd.sh"
destination = "/home/ubuntu/worker-node-cmd.sh"
}

#

# Install containerd, kubelet, kubeadm, kubectl

#

provisioner "remote-exec" {
inline = [
"chmod +x /home/ubuntu/worker-node-cmd.sh",
"sudo bash /home/ubuntu/worker-node-cmd.sh"
]
}

#

# Upload join command generated by control plane

#

provisioner "file" {
source      = "./join-command.sh"
destination = "/home/ubuntu/join-command.sh"
}

#

# Join worker to cluster

#

provisioner "remote-exec" {
inline = [
"chmod +x /home/ubuntu/join-command.sh",
"sleep 10",
"sudo bash /home/ubuntu/join-command.sh"
]
}
}
